---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: workloads
  namespace: flux-system
spec:
  prune: true
  interval: 2m0s
  path: ./cluster-name
  sourceRef:
    kind: GitRepository
    name: gitops-workloads
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
---