apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  releaseName: sealed-secrets
  interval: 5m
  install: 
    createNamespace: true
  chart:
    spec:
      chart: sealed-secrets
      version: '2.1.6' # Corresponds to 0.17.5
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repository
        namespace: flux-system
      interval: 1m


