---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-name-external-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-name-external-secrets-iam
  interval: 1m0s
  path: ./tools/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
  timeout: 2m
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: cluster-name-external-secrets
    namespace: flux-system
  patches:
    - target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: external-secrets
        namespace: flux-system
      patch: |-
        - op: add
          path: /spec/kubeConfig
          value: 
            secretRef:
              name: cluster-name-eks-connection
        - op: replace
          path: /metadata/name
          value: cluster-name-external-secrets
---