apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: gitops-workloads
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: gitops-workloads
  timeout: 60s
  url: ssh://git@github.com/iamahgoub/gitops-workloads