---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: commercial-prod-sealed-secrets
  namespace: flux-system
spec:
  dependsOn:
  - name: commercial-prod-external-secrets-config
  interval: 30s
  path: ./tools/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: commercial-prod-sealed-secrets
    namespace: flux-system
  - kind: Deployment
    name: sealed-secrets
    namespace: sealed-secrets
  validation: client
  timeout: 2m
  patches:
    - target:
        group: helm.toolkit.fluxcd.io
        kind: HelmRelease
        name: sealed-secrets
        namespace: flux-system
      patch: |-
        - op: add
          path: /spec/kubeConfig
          value: 
            secretRef:
              name: commercial-prod-eks-connection
        - op: replace
          path: /metadata/name
          value: commercial-prod-sealed-secrets