---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crossplane
  namespace: flux-system
spec:
  prune: true
  interval: 3m0s
  path: ./tools/crossplane
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---