---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: external-secrets-repository
  namespace: external-secrets
spec:
  interval: 5m
  url: https://charts.external-secrets.io